### ISSUE TITLE
Mob animations not playing for first connected client

### ISSUE THREAD

**Issue by zaneiel** [vis2k/uMMORPG_CE#28]
Mob animations not playing for first connected client.

Fresh install of uMMORPG CE
host Ubuntu 18.04 6 gigs of ram 4 vcpu 2.2 GHZ headless unity 2019.4.4f1

when logging in as the only client, animations are not working on the bandit mobs nor bandit mob boss.
using the monster spawn scroll works and is animated as intended.
sometimes the newly spawned bandits will be animated after you kill them.
logging in more than 1 client and then relogging the first client fixes the issue
So a workaround has been to relog the first client after you have more clients connected.

**Comment by miwarnec** [comment]
hey, thanks for reporting.
finally fixed this issue. it was an unnecessary IsWorthUpdating check in Monster.LateUpdate before animating:

![2020-10-05_16-47-03](https://user-images.githubusercontent.com/16416509/95094663-6f2a5c00-072a-11eb-959c-1972fbb98058.png)

fixed in next version. remove the check if you don't want to wait.

**Comment by zaneiel** [comment]
Awesome, thanks for the update.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
